name: 'Query YAML config as outputs'
description: 'Query YAML config and map the result as outputs'
author: hello@cloudposse.com
branding:
  icon: 'wind'
  color: 'white'
inputs:
  query:
    required: true
    description: "JQ Query"
    default: "."
  config:
    required: true
    description: "YAML config"
runs:
  using: "composite"
  steps:
    - id: context
      shell: bash
      run: |
          echo "::set-output name=action-result::test"

