name: 'Query YAML config as outputs'
description: 'Query YAML config and map the result as outputs'
author: hello@cloudposse.com
branding:
  icon: 'wind'
  color: 'white'
inputs:
  query:
    required: true
    description: "JQ Query"
    default: "."
  config:
    required: true
    description: "YAML config"
runs:
  using: "composite"
  steps:
    - uses: cloudposse-github-actions/install-gh-releases@v1
      with:
        cache: true
        config: |-
          jqlang/jq: jq-1.7
          mikefarah/yq: v4.30.1

    - shell: bash
      run: |-
        jq --help
        yq --help

#  env:
#    QUERY: ${{ inputs.query }}
#    CONFIG: ${{ inputs.config }}
