name: Test example negative
on:
#  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
#  #
#  # Added pull_request to register workflow from the PR.
#  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
#  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        id: current
        with:
          query: .foo
          config: |
            test: foo
            bar: bar

    outputs:
      result: ${{ steps.current.conclusion }}
      test: "${{ steps.current.outputs.test }}"
      bar: "${{ steps.current.outputs.bar }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'failure'
          actual: "${{ needs.test.outputs.result }}"

      - uses: nick-fields/assert-action@v1
        with:
          expected: ''
          actual: "${{ needs.test.outputs.test }}"

      - uses: nick-fields/assert-action@v1
        with:
          expected: ''
          actual: "${{ needs.test.outputs.bar }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
